"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import datetime

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'b@8w6&tlbz!ypk1b=0r$vvutiq4eeb##i#ap!^(kq25%a6dyal'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
APPEND_SLASH = False

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CSRF_COOKIE_NAME = "XSRF-TOKEN"
ROOT_URLCONF = 'mysite.urls'
CORS_ORIGIN_ALLOW_ALL = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['web-client/dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {

    'DEFAULT_PERMISSION_CLASSES': (

        # 'rest_framework.permissions.IsAuthenticated',
        'web.permissions.MyIsAuthenticated',

    ),

    # 'DEFAULT_AUTHENTICATION_CLASSES': (

    #     'rest_framework.authentication.TokenAuthentication',
    #     # 'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
    #     # 'rest_framework.authentication.BasicAuthentication',
    #     'rest_framework.authentication.SessionAuthentication',

    # ),

    # 'PAGINATE_BY': 10
}

JWT_AUTH = {
    # 表示issue出去的token多久过期，默认是5mins
    'JWT_EXPIRATION_DELTA': datetime.timedelta(seconds=300),
    # 表示某个token被issue出去后，在多久间隔内可以用它来刷新以便获取新的token，默认是7天
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=7),
}

WSGI_APPLICATION = 'mysite.wsgi.application'

TOKEN_LIFE_TIME = 10

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mysite',
        'USER': 'root',
        'PASSWORD': 'ysh123456',
    }
}

# MYSQL_PATH = 'mysql+pymysql://root:ysh123456@127.0.0.1:3306/mysite'
MYSQL_PATH = 'mysql+mysqlconnector://root:ysh123456@127.0.0.1:3306/mysite'

ADMIN_INFO = {'username': 'admin', 'password': '21232f297a57a5a743894a0e4a801fc3', 'role': 'superuser', 'email': '540309204@qq.com'}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
